ner_tags = {
}

pos_tags = {
    'LS': 'list item marker',
    'TO': '"to" as preposition or infinitive marker',
    'VBN': 'verb, past participle',
    "''": 'closing quotation mark',
    'WP': 'WH-pronoun',
    'UH': 'interjection',
    'VBG': 'verb, present participle or gerund',
    'JJ': 'adjective or numeral, ordinal',
    'VBZ': 'verb, present tense, 3rd person singular',
    '--': 'dash',
    'VBP': 'verb, present tense, not 3rd person singular',
    'NN': 'noun, common, singular or mass',
    'DT': 'determiner',
    'PRP': 'pronoun, personal',
    ':': 'colon or ellipsis',
    'WP$': 'WH-pronoun, possessive',
    'NNPS': 'noun, proper, plural',
    'PRP$': 'pronoun, possessive',
    'WDT': 'WH-determiner',
    '(': 'opening parenthesis',
    ')': 'closing parenthesis',
    '.': 'sentence terminator',
    ',': 'comma',
    '``': 'opening quotation mark',
    '$': 'dollar',
    'RB': 'adverb',
    'RBR': 'adverb, comparative',
    'RBS': 'adverb, superlative',
    'VBD': 'verb, past tense',
    'IN': 'preposition or conjunction, subordinating',
    'FW': 'foreign word',
    'RP': 'particle',
    'JJR': 'adjective, comparative',
    'JJS': 'adjective, superlative',
    'PDT': 'pre-determiner',
    'MD': 'modal auxiliary',
    'VB': 'verb, base form',
    'WRB': 'Wh-adverb',
    'NNP': 'noun, proper, singular',
    'EX': 'existential there',
    'NNS': 'noun, common, plural',
    'SYM': 'symbol',
    'CC': 'conjunction, coordinating',
    'CD': 'numeral, cardinal',
    'POS': 'genitive marker'
}
